config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "bills#index"
  resources :items
  resources :bills, only: [:index,:new,:create, :show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bill.rb
class Bill < ApplicationRecord
	belongs_to :user, optional: true
	belongs_to :creator, class_name: "User", foreign_key: "created_by", optional: true
	has_many :bill_items, dependent: :destroy

  def save_bill_items(params, current_user)
    bill_items = Hash[params[:item_id].zip(params[:quantity])] 
    total_amount = 0
    net_amount = 0
    
    bill_items.each do |item_id, quantity|
      item = current_user.items.where("id = ?", item_id).first
      if item.present?  
        total_amount = total_amount + (item.price * quantity.to_i)
        BillItem.create(item_id: item_id, quantity: quantity, bill_id: id)
      end
    end
    net_amount = total_amount + (total_amount * 0.15)

    self.update_attributes(total_amount: total_amount, net_amount: net_amount)
  end
end

app/models/bill_item.rb
class BillItem < ApplicationRecord
	belongs_to :item
end

app/models/item.rb
class Item < ApplicationRecord
	belongs_to :creator, class_name: "User", foreign_key: "created_by", optional: true
end

app/models/items_tag.rb
class ItemsTag < ApplicationRecord
  belongs_to :item
  belongs_to :tag
end

app/models/tag.rb
class Tag < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :bills, class_name: "Bill", foreign_key: "created_by"
  has_many :items, class_name: "Item", foreign_key: "created_by"
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/bills_controller.rb
class BillsController < ApplicationController
  def index
    @bills = current_user.bills.order("created_at DESC")
  end

  def show
    @bill = current_user.bills.find_by_id(params[:id])
    if @bill.nil?
      flash[:alert] = "Bill not found."
      redirect_to bills_path
      return
    end
    @bill_items = @bill.bill_items
  end

  def new
    @items = current_user.items
    @bill = Bill.new
  end

  def create
    @bill = Bill.new(bill_params)
    respond_to do |format|
      if @bill.save
        @bill.update_attribute :created_by, current_user.id
        @bill.save_bill_items(params, current_user)

        format.html { redirect_to root_path, notice: 'Item was successfully created.' }
        format.json { render :show, status: :created, location: @bill }
      else
        format.html { render :new }
        format.json { render json: @bill.errors, status: :unprocessable_entity }
      end
    end
  end

  private
  
  def bill_params
    params.require(:bill).permit(:bill_to)
  end

end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only: [:show, :edit, :update, :destroy]

  def index
    @items = current_user.items.order("created_at DESC")
  end

  def show
  end

  def new
    @item = Item.new
  end

  def edit
  end

  def create
    @item = Item.new(item_params)

    respond_to do |format|
      if @item.save
        @item.update_attribute :created_by, current_user.id 
        format.html { redirect_to items_path, notice: 'Item was successfully created.' }
        format.json { render :show, status: :created, location: @item }
      else
        format.html { render :new }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @item.update(item_params)
        format.html { redirect_to @item, notice: 'Item was successfully updated.' }
        format.json { render :show, status: :ok, location: @item }
      else
        format.html { render :edit }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @item.destroy
    respond_to do |format|
      format.html { redirect_to items_url, notice: 'Item was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_item
      @item = Item.find(params[:id])
    end

    def item_params
      params.require(:item).permit(:name, :price, :tags)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bills_helper.rb
module BillsHelper
end

app/helpers/bootstrap_flash_helper.rb
module BootstrapFlashHelper
  ALERT_TYPES = [:success, :info, :warning, :danger] unless const_defined?(:ALERT_TYPES)

  def bootstrap_flash(options = {})
    flash_messages = []
    flash.each do |type, message|
      # Skip empty messages, e.g. for devise messages set to nothing in a locale file.
      next if message.blank?

      type = type.to_sym
      type = :success if type == :notice
      type = :danger  if type == :alert
      type = :danger  if type == :error
      next unless ALERT_TYPES.include?(type)

      tag_class = options.extract!(:class)[:class]
      tag_options = {
        class: "alert fade in alert-#{type} #{tag_class}"
      }.merge(options)

      close_button = content_tag(:button, raw("&times;"), type: "button", class: "close", "data-dismiss" => "alert")

      Array(message).each do |msg|
        text = content_tag(:div, close_button + msg, tag_options)
        flash_messages << text if msg
      end
    end
    flash_messages.join("\n").html_safe
  end
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/bills/index.html.erb
<%=link_to "Create Bill", new_bill_path, class:"btn btn-success create-btn" %>
<h1>Bills</h1>

<table class="table table-striped table-hover" id="billsTable">
  <thead>
    <tr>
      <th>Bill To</th>
      <th>Total Amount</th>
      <th>Net Amount</th>
      <th>Created by</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @bills.each do |bill| %>
      <tr>
        <td><%= bill.bill_to %></td>
        <td><%= bill.total_amount.round(2) %></td>
        <td><%= bill.net_amount.round(2) %></td>
        <td><%= bill.creator.email %></td>
        <td><%= link_to "View Details", bill %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/bills/new.html.erb
<div class="create_bill_page">
  <div class="login-form">
    <%= form_for @bill, url: bills_path do |f| %>
      <% if @bill.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@bill.errors.count, "error") %> prohibited this bill from being saved:</h2>

          <ul>
          <% @bill.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
          </ul>
        </div>
      <% end %>

      <h2 class="text-center">Create Bill</h2>   
      <div class="form-group">
        <div class="input-group">
          <%= f.text_field :bill_to, class: "form-control", required: true, placeholder:"Customer Name" %>    
        </div>
      </div>

      <div class="item_header_cntr"> 
        <div class="col-md-6 item_header">Item Name</div>
        <div class="col-md-2 item_header">Item Price</div>
        <div class="col-md-2 item_header">Quantity</div>
        <div class="col-md-2 item_header">Total</div>
        <div class="cb"></div>
      </div>
      <div class="bill_item row">
        <div class="form-group col-md-6">
          <div class="input-group">
            <%= select_tag 'item_id[]', options_for_select(@items.collect{ |u| [u.name, u.id, {'data-price' => u.price}] }), {prompt: "- Select Item -", class: "form-control select_item", id: "", required: true} %>
          </div>
        </div>
        <div class="col-md-2">
          <p class="item_amount">0.00</p>
        </div>
        <div class="form-group col-md-2">
          <div class="input-group">
            <%= text_field_tag "quantity[]","", class: "form-control numbers_only item_qty", required: true, placeholder: "Quantity", id:"", maxlength: "3" %>
          </div>
        </div>
        <div class="col-md-2">
          <p class="amount">0.00</p>
        </div>
        <div class="cb"></div>

        <div class="remove"></div>
      </div>  
      <%= link_to "+ Add Item", "javascript:void(0)", class: "add_item"%>
      <div class="total_amount_sec">
        <div><span class="calc">Total: </span><span class="total_amount">0.00</span></div>
        <div><span class="calc">Net Amount(Total + Tax): </span><span class="net_amount">0.00</span></div>
      </div>
      <div class="form-group">
        <%= f.submit "Save", :class => "btn btn-primary login-btn btn-block" %>
      </div>
      <div class="clearfix"></div>
    <% end %>
  </div>

</div>

app/views/bills/show.html.erb

<div class="bill_show">
  <div>
    <b>Total Amount: </b> <%= @bill.total_amount%>
  </div>
  <div>
    <b>Net Amount (Total + Tax): </b> <%= @bill.net_amount%>
  </div>
</div>
<table class="table table-striped table-hover">
  <thead>
    <tr>
      <th>Item Purchased</th>
      <th>Quantity</th>
      <th>Item Price</th>
    </tr>
  </thead>

  <tbody>
    <% @bill_items.each do |bill_item| %>
      <tr>
        <td><%= bill_item.item.name %></td>
        <td><%= bill_item.item.price %></td>
        <td><%= bill_item.quantity %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/items/_form.html.erb
<div class="login-form">
  <%= form_with(model: item, local: true) do |f| %>
    <% if item.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(item.errors.count, "error") %> prohibited this item from being saved:</h2>

        <ul>
        <% item.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>
    <h2 class="text-center"><%= item.new_record? ? "Add Item" : "Edit Item"%></h2>   
    <div class="form-group">
      <div class="input-group">
          <%= f.text_field :name, class: "form-control", required: true, placeholder:"Name" %>    
        </div>
    </div>
    <div class="form-group">
      <div class="input-group">
          <%= f.text_field :price, class: "form-control float_only", required: true, placeholder:"Price" %>    
        </div>
    </div>
    <div class="form-group">
      <div class="input-group">
          <%= f.text_field :tags, class: "form-control tags", placeholder: "Tags" %>    
        </div>
    </div>

    <div class="form-group">
      <%= f.submit item.new_record? ? "Save" : "Update", :class => "btn btn-primary login-btn btn-block" %>
    </div>
    <div class="clearfix"></div>
  <% end %>
</div>

app/views/items/edit.html.erb
<%= render 'form', item: @item %>

app/views/items/index.html.erb
<%=link_to "Add Item", new_item_path, class:"btn btn-success create-btn" %>

<h1>Items</h1>

<table class="table table-striped table-hover" id="itemsTable">
  <thead>
    <tr>
      <th>Name</th>
      <th>Price</th>
      <th>Tags</th>
      <th>Created by</th>
      <th>Action</th>
    </tr>
  </thead>

  <tbody>
    <% @items.each do |item| %>
      <tr>
        <td><%= link_to item.name, item %></td>
        <td><%= item.price %></td>
        <td><%= item.tags %></td>
        <td><%= item.creator.email %></td>
        <td><%= link_to 'Edit', edit_item_path(item) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/items/new.html.erb
<%= render 'form', item: @item %>

app/views/items/show.html.erb
<div class="item_show_page">
  <p>
    <strong>Name:</strong>
    <%= @item.name %>
  </p>

  <p>
    <strong>Price:</strong>
    <%= @item.price %>
  </p>
  <p>
    <strong>Tags:</strong>
    <%= @item.tags %>
  </p>

  <p>
    <strong>Created by:</strong>
    <%= @item.creator.email %>
  </p>

  
</div>
<%= link_to 'Edit', edit_item_path(@item) %> |
<%= link_to 'Back', items_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>POS System</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <%= bootstrap_flash %>
      <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
          <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="/">POS System</a>
          </div>
          <div id="navbar" class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
              <li ><a href="/">Home</a></li>
              <% if user_signed_in? %>
                <li ><a href="/items">Items</a></li>
                <li ><a href="/bills">Bills</a></li>
                <li><%= link_to('Logout', destroy_user_session_path, method: :delete) %></li>
                <li class="active"><a href="javascript:void(0)">Logged in as: <%=current_user.email%></a></li>
              <% else %>
                <li>
                  <%= link_to('Login', new_user_session_path)  %>  
                </li>
                <li>
                  <%= link_to('SignUp', new_user_registration_path)  %>  
                </li>
              <% end %>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </nav>
    </header>  
    <div class="main_cntr">
      <%= yield %>
    </div>
  </body>
</html>